#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# create folders
mkdir -p \
    /app/www/public/apps \
    /app/www/public/config \
    /app/www/public/themes \
    /config/www/nextcloud/apps \
    /config/www/nextcloud/config \
    /config/www/nextcloud/themes \
    /data

# migrate legacy install (copy inside container)
if [ -f /config/www/nextcloud/version.php ]; then
    echo "Migrating legacy install"
    rsync -rlD --remove-source-files --exclude-from=/app/upgrade.exclude /config/www/nextcloud/ /app/www/public/
    rsync -rlD --remove-source-files --include '/version.php' --exclude '/*' /config/www/nextcloud/ /app/www/public/
    rm -rf /config/www/nextcloud/updater/
    find \
        /config/www/nextcloud/ \
        -type d -empty \
        ! -path "/config/www/nextcloud/apps" \
        ! -path "/config/www/nextcloud/config" \
        ! -path "/config/www/nextcloud/themes" \
        -delete
    sed -i "s|/config/www/nextcloud/cron.php|/app/www/public/cron.php|g" /config/crontabs/root
    touch /tmp/migration
fi

# symlink config folders
for dir in apps config themes; do
    if [ "$(readlink /app/www/public/${dir})" != "/config/www/nextcloud/${dir}" ]; then
        rm -rf "/app/www/public/${dir}"
        ln -s "/config/www/nextcloud/${dir}" "/app/www/public/${dir}"
        lsiown abc:abc "/config/www/nextcloud/${dir}" "/app/www/public/${dir}"
    fi
done

# symlink data folder
if [ "$(readlink /app/www/public/data)" != "/data" ]; then
    rm -rf /app/www/public/data
    ln -s /data /app/www/public/data
    lsiown abc:abc /data /app/www/public/data
fi

# get versions
image_version=$(php -r "require '/app/www/src/version.php'; echo implode('.', \$OC_Version);" 2>/dev/null)
installed_version=$(php -r "require '/config/www/nextcloud/config/config.php'; echo \$CONFIG['version'];" 2>/dev/null)
if [ "${installed_version}" = "" ]; then
    installed_version="0.0.0.0"
fi

# compare versions
vergte() { printf '%s\n%s' "${2}" "${1}" | sort -C -V; }
vergt() { ! vergte "${2}" "${1}"; }
verlte() { printf '%s\n%s' "${1}" "${2}" | sort -C -V; }
verlt() { ! verlte "${2}" "${1}"; }

if vergt "${installed_version}" "${image_version}"; then
    echo "Can't start Nextcloud because the version of the data (${installed_version}) is higher than the docker image version (${image_version}) and downgrading is not supported. Are you sure you have pulled the newest image version?"
    sleep infinity
fi

# initialize nextcloud
if vergt "${image_version}" "${installed_version}" || [ -f /tmp/migration ]; then
    echo "Initializing nextcloud ${image_version} ..."
    if [ "${installed_version}" != "0.0.0.0" ]; then
        echo "Upgrading nextcloud from ${installed_version} ..."
        occ app:list | sed -n "/Enabled:/,/Disabled:/p" >/tmp/list_before
    fi

    rsync -rlD --exclude-from=/app/upgrade.exclude /app/www/src/ /app/www/public/
    for dir in apps config themes; do
        if [ -z "$(ls -A /app/www/public/${dir}/ 2>/dev/null)" ]; then
            rsync -rlD --include "/${dir}" --exclude '/*' /app/www/src/ /config/www/nextcloud/
        fi
    done
    if [ -z "$(ls -A /app/www/public/data/ 2>/dev/null)" ]; then
        rsync -rlD --include "/data" --exclude '/*' /app/www/src/ /
    fi
    rsync -rlD --include '/version.php' --exclude '/*' /app/www/src/ /app/www/public/

    echo "Setting permissions"
    lsiown abc:abc -R \
        /app/www/public \
        /config/www/nextcloud

    if [ "${installed_version}" = "0.0.0.0" ]; then
        # Install
        echo "New nextcloud instance"
        echo "Please run the web-based installer on first connect!"
    else
        # Upgrade
        occ upgrade

        occ app:list | sed -n "/Enabled:/,/Disabled:/p" >/tmp/list_after
        echo "The following apps have been disabled:"
        diff /tmp/list_before /tmp/list_after | grep '<' | cut -d- -f2 | cut -d: -f1
    fi

    rm -f /tmp/list_before /tmp/list_after
    echo "Initializing finished"
fi

rm -f /tmp/migration

# permissions
lsiown abc:abc \
    /app/www/public \
    /config/www/nextcloud

# setup config
if occ config:system:get installed >/dev/null 2>&1; then
    if ! occ config:system:get memcache.local >/dev/null 2>&1; then
        occ config:system:set memcache.local --value='\\OC\\Memcache\\APCu'
    fi
fi

if (occ app:list --no-interaction | grep -q richdocumentscode) 2>/dev/null; then
    echo "Removing CODE Server"
    APP=$(occ app:list --no-interaction | grep richdocumentscode | awk -F ' ' '{print $2}' | tr -d ':')
    occ app:remove --no-interaction "${APP}" 2>/dev/null
fi
