#!/usr/bin/with-contenv bash

# permissions
chown abc:abc \
	/config \
	/data
chown -R abc:abc  \
	/var/lib/nginx

# directories
if [ ! -d /config/log/cron ]; then
	mkdir -p /config/log/cron
fi
	
# EOF
