#!/usr/bin/with-contenv bash

# permissions
chown abc:abc \
	/config \
	/data
chown -R abc:abc  \
	/var/lib/nginx

sudo -u abc php7 /config/www/nextcloud/occ db:add-missing-indices
sudo -u abc php7 /config/www/nextcloud/occ db:convert-filecache-bigint
