#!/usr/bin/with-contenv bash

# create folders
mkdir -p \
    "${NEXTCLOUD_PATH}" \
    /config/crontabs

# install app
if [ ! -e "${NEXTCLOUD_PATH}/index.php" ]; then
    tar xf /app/nextcloud.tar.bz2 -C \
        "${NEXTCLOUD_PATH}" --strip-components=1
    chown abc:abc -R \
        "${NEXTCLOUD_PATH}"
    chmod +x "${NEXTCLOUD_PATH}/occ"
fi

# set cronjob
if [[ ! -f /config/crontabs/root ]]; then
    cp /defaults/root /config/crontabs/root
fi
sed -i "s|s6-setuidgid abc php[78] -f /config/www/nextcloud/cron.php|s6-setuidgid abc php -f /config/www/nextcloud/cron.php|" /config/crontabs/root
cp /config/crontabs/root /etc/crontabs/root
