#!/usr/bin/with-contenv bash

# copy config
if [[ ! -f /config/www/nextcloud/config/config.php ]]; then
    cp /defaults/config.php /config/www/nextcloud/config/config.php
fi

# permissions
chown abc:abc \
    /config/www/nextcloud/config/config.php
