#!/usr/bin/with-contenv bash

[[ ! -f /config/www/nextcloud/config/config.php ]] && cp /defaults/config.php /config/www/nextcloud/config/config.php

chown abc:abc /config/www/nextcloud/config/config.php
